my_list = ["leaf"
           , "cream"
           , "pickles"
           , "vinegar"
           , "gouda"
           , "almond"
           , "fire"
           , "orbit"
           , "spider"
           , "symbol"
           , "java"
           , "javascript"
           , "python"
           , "kotlin"
           , "today"
           , "march"
           , "clock"
           , "people"
           , "mobile"
           , "shirt"
           , "chair"
           , "planet"
            ]